

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents node_modules from being overwritten by the volume
    networks:
      - webnet
    environment:
      VITE_BACKEND_URL: http://localhost:8000

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/
    networks:
      - webnet

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - webnet

volumes:
  mongo-data:

networks:
  webnet:
